(function() {var implementors = {
"archive":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"archive/errors/enum.Error.html\" title=\"enum archive::errors::Error\">Error</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"archive/errors/enum.TimeError.html\" title=\"enum archive::errors::TimeError\">TimeError</a>"]],
"binary_input":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"binary_input/enum.Error.html\" title=\"enum binary_input::Error\">Error</a>"]],
"cow_dedupe":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"cow_dedupe/errors/enum.Error.html\" title=\"enum cow_dedupe::errors::Error\">Error</a>"]],
"enc":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"enc/errors/enum.Error.html\" title=\"enum enc::errors::Error\">Error</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"enc/errors/struct.PasswordHashError.html\" title=\"struct enc::errors::PasswordHashError\">PasswordHashError</a>"]],
"file_bmp_codec":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"file_bmp_codec/errors/enum.Error.html\" title=\"enum file_bmp_codec::errors::Error\">Error</a>"]],
"forward":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"forward/errors/enum.Error.html\" title=\"enum forward::errors::Error\">Error</a>"]],
"http_server":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"http_server/errors/enum.Error.html\" title=\"enum http_server::errors::Error\">Error</a>"]],
"ncat":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"ncat/errors/enum.Error.html\" title=\"enum ncat::errors::Error\">Error</a>"]],
"phone_transfer":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"phone_transfer/errors/enum.Error.html\" title=\"enum phone_transfer::errors::Error\">Error</a>"]],
"serial_cat":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"serial_cat/errors/enum.Error.html\" title=\"enum serial_cat::errors::Error\">Error</a>"]],
"tcp_crypto_tunnel":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"tcp_crypto_tunnel/errors/enum.Error.html\" title=\"enum tcp_crypto_tunnel::errors::Error\">Error</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()